### ISSUE TITLE
David's todo

### ISSUE THREAD

**Issue by DavidL0914** [CSA-Coders-2025/Planning-Repository-Issue-House-#21]
- [x] Continue testing hack generator using our Google API
- [x] Connect the backend to frontend
- [x] Integrate with rest of team's code
- [x] Connect the feature with other features in the group so it fits better together (likely integrate with the area where Mr. M can create lessons/agenda on the calendar for students to see)
