### ISSUE TITLE
Team Hanlun, Miheer, Sharon, David, Eshaan, Beijan Integration Plan

### ISSUE THREAD

**Issue by hanlunli** [CSA-Coders-2025/Planning-Repository-Issue-House-#41]
## Hanlun
- I will be working on integrating my feature (dice) of the "casino" game with the login system
- Estimated time: ~3 days
- More details: https://github.com/CSA-Coders-2025/Planning-Repository-Issue-House-/issues/38
## Beijan
- I will be working on the leaderboard system with the synergy group in period 3 and integrate it with their app
- Estimated time: 5 days
## Miheer
- I will incorporate the student page so that it works with the student backend instead of a working in a different database. 
- Estimated Time: 4-5 days
## Eshaan
- I will incorporate my public confirmation board and teacher manage page with period 3 synergy grading system
- I will also incorporate it with the new shared backend and all my methods
- Estimated time 4-5 days

## Sharon
- I will be working with CSA synergy group in period 3 to integrate our grading system with theres 
- around 5 days 

## David
- Work with Seed tracker group and CSA synergy group to integrate our AI assignment creator and grader
- Around 5 days
- More details: https://github.com/CSA-Coders-2025/Planning-Repository-Issue-House-/issues/23

**Note: More detailed personal issues underneath**

**Comment by DavidL0914** [comment]
## Hanlun
- Scrum Master Evaluation:
   - created team issue detailing integration planning and future goals.
- Link to integration plans: https://github.com/CSA-Coders-2025/Planning-Repository-Issue-House-/issues/38

## To Do:
- Integrate the "dice" game into the user database
- Current user table:
![Image](https://github.com/user-attachments/assets/f46ddb88-4b87-4987-a837-021f0e5a90c9)
- Current flowchart for backend:
![Image](https://github.com/user-attachments/assets/2ca31b53-b2e4-4b26-8a7b-21d2fd3451d5)
- connect my feature onto the login system, also work on the landing page with my group
- Backend integration: we will need a "balance" column in the user database [link to current backend integration request](https://github.com/orgs/CSA-Coders-2025/projects/3/views/8?pane=issue&itemId=88323910&issue=CSA-Coders-2025%7CPlanning-Repository-Issue-House-%7C43)

## Checklist:
- [ ] create landing page
- [ ] integrate dice game with login (balance)
- [ ] create balance column in backend (integrate with new users db)
- [ ] integrate frontend with gamify (make sure theme is consistent)
- [ ] communicate w/ project group for future planning

## Future Collegeboard FRQ Plan:
- doing 2d arrays with Sharon and David
- planning on using 2015 frq 3 for reference [link to frq 2015](https://secure-media.collegeboard.org/digitalServices/pdf/ap/ap15_frq_computer_science_a.pdf)
- coordinating with group for future plans

**Comment by DavidL0914** [comment]
## David
- **Scrum Master Evaluation** by Hanlun:
   - Project team issue is very detailed, with a large amount of very specific changes listed. Seems very helpful for integration
## My feature
- Part of Synergy team
- AI Grader - I created the question generator page.
## Synergy team plans
- AI Grader Integration Plans - https://github.com/orgs/CSA-Coders-2025/projects/3/views/6?sliceBy%5Bvalue%5D=In+review&pane=issue&itemId=88324879&issue=CSA-Coders-2025%7CPlanning-Repository-Issue-House-%7C45
- AI Grader Future Plans - https://github.com/CSA-Coders-2025/Planning-Repository-Issue-House-/issues/23
## Commits/Analytics
- Commits (Completed so far): Added way to save and store created assignments for future reference in db. Added styling changes for better integration.
![Image](https://github.com/user-attachments/assets/4bfa117b-30a0-4601-ba1a-2470a6081198)
- Saved question feature:
![{25123B17-B2C4-4A27-8EF2-42B139409DC6}](https://github.com/user-attachments/assets/8bfb7d18-ee5d-4d58-ba37-0bf9ffbf322c)
- Database work
![{FFEB47E2-70C3-45C9-800D-0E73DBE2F9B9}](https://github.com/user-attachments/assets/ce71c1c3-fd89-4fe0-91d7-466e5246ce08)
- Flowchart for visualization:
![{9DD5F4B7-5B90-4207-A925-2F1FF6445F16}](https://github.com/user-attachments/assets/36ca2224-a7f4-4858-a23f-9029ea2b9790)
## To-Do Checklist/Future Plans:
- [ ] Connect generator page to login system - no access to page without user login/cookies
- [ ] Save assignments under each account in database so that users can only see the questions they have saved
- [ ] Add answers to generated FRQ questions that can also be saved in db
- [ ] Finish integrating with Synergy team

**Comment by eshaank1** [comment]
## Eshaan
- **Scrum Master Evaluation** for Hanlun:
   - Project team issue is detailed, with a specific changes that are helpful for integration.
## My feature
- Part of Seed Tracker team
- Teacher Page - I created the teacher viewpage where they recieve the student's seed requests and approve/deny or manually change the values
- Confirmation Page - I created the confirmation page for students to confirm their seed request was sent
## Synergy team plans
- AI Grader Integration Plans - https://github.com/orgs/CSA-Coders-2025/projects/3/views/9?pane=issue&itemId=89571985&issue=CSA-Coders-2025%7CPlanning-Repository-Issue-House-%7C69
## Commits/Analytics
- Commits (Including end of last tri to current): Added way to change values in the database from teacher page. Added new styling changes for better integration.
![Image](https://github.com/user-attachments/assets/e8583acf-1fcc-4c5f-abc6-f14c40cbff38)
- Teacher page:
![Image](https://github.com/user-attachments/assets/9cc381cd-4496-4182-8527-6e8eaddae0b1)
- Database:
![Image](https://github.com/user-attachments/assets/5f0e8dc1-306f-4f53-9910-3e9eceb698e7)
## To-Do Checklist/Future Plans:
- [ ] Connect teacher/student pages with login system to make the right one show up per account
- [ ] Add a way to integrate scores with the Synergy Gradebook
- [ ] Finish integrating with Synergy team
