### ISSUE TITLE
Individual Planning Checkpoint - BEDHMS

### ISSUE THREAD

**Issue by hanlunli** [CSA-Coders-2025/Planning-Repository-Issue-House-#79]
## Hanlun
- I will be working on integrating my feature (dice) of the "casino" game with the login system
- Estimated time: ~3 days
- More details: https://github.com/CSA-Coders-2025/Planning-Repository-Issue-House-/issues/38
## Beijan
- I will be working on the leaderboard system with the synergy group in period 3 and integrate it with their app
- Estimated time: 5 days
## Miheer
- I will incorporate the student page so that it works with the student backend instead of a working in a different database. 
- Estimated Time: 4-5 days
## Eshaan
- I will incorporate my public confirmation board and teacher manage page with period 3 synergy grading system
- I will also incorporate it with the new shared backend and all my methods
- Estimated time 4-5 days

## Sharon
- I will be working with CSA synergy group in period 3 to integrate our grading system with theres 
- around 5 days 

## David
- Work with Seed tracker group and CSA synergy group to integrate our AI assignment creator and grader
- Around 5 days
- More details: https://github.com/CSA-Coders-2025/Planning-Repository-Issue-House-/issues/23

**Comment by hanlunli** [comment]
## Hanlun
- Scrum Master Evaluation:
   - created team issue detailing integration planning and future goals.
- Link to integration plans: https://github.com/CSA-Coders-2025/Planning-Repository-Issue-House-/issues/38

## Analytics:
- Total commits
![Image](https://github.com/user-attachments/assets/bc2d8b28-20a0-4f58-be0d-709b2b72cb25)
- I don't have much code yet, but I did update the score calculation to make the game more fair. [link to commit](https://github.com/Imaad08/NITD_2025/commit/76024b5a79a6f9463d97661fd332ad88bdefe7c8)

## To Do:
- Integrate the "dice" game into the user database
- Current user table:
![Image](https://github.com/user-attachments/assets/f46ddb88-4b87-4987-a837-021f0e5a90c9)
- Current flowchart for backend:
![Image](https://github.com/user-attachments/assets/2ca31b53-b2e4-4b26-8a7b-21d2fd3451d5)
- connect my feature onto the login system, also work on the landing page with my group
- Backend integration: we will need a "balance" column in the user database [link to current backend integration request](https://github.com/orgs/CSA-Coders-2025/projects/3/views/8?pane=issue&itemId=88323910&issue=CSA-Coders-2025%7CPlanning-Repository-Issue-House-%7C43)
- merged master in preparation for future integration [link to commit](https://github.com/CSA-Coders-2025/CSA_Combined_Frontend_Fork/commit/aac778a07752f999e030444bcf76ec2e3e00090e)

## Checklist:
- [ ] create landing page
- [ ] integrate dice game with login (balance)
- [ ] create balance column in backend (integrate with new users db)
- [ ] integrate frontend with gamify (make sure theme is consistent)
- [ ] communicate w/ project group for future planning

## Future Collegeboard FRQ Plan:
- doing 2d arrays with Sharon and David
- planning on using 2015 frq 3 for reference [link to frq 2015](https://secure-media.collegeboard.org/digitalServices/pdf/ap/ap15_frq_computer_science_a.pdf)
- coordinating with group for future plans

## Done so far:
- met up with last tri group in order to discuss plans for integration
- split up workload for integration:
- Saaras: landing page + personal feature integration
- Hanlun: personal feature integration
- Arthur: personal feature integration
- Alisha: personal feature integration

**Comment by DavidL0914** [comment]
## David
- **Scrum Master Evaluation** by Hanlun:
   - Project team issue is very detailed, with a large amount of very specific changes listed. Seems very helpful for integration
## My feature
- Part of Synergy team
- AI Grader - I created the question generator page.
## Synergy team plans
- AI Grader Integration Plans - https://github.com/orgs/CSA-Coders-2025/projects/3/views/6?sliceBy%5Bvalue%5D=In+review&pane=issue&itemId=88324879&issue=CSA-Coders-2025%7CPlanning-Repository-Issue-House-%7C45
- AI Grader Future Plans - https://github.com/CSA-Coders-2025/Planning-Repository-Issue-House-/issues/23
## Commits/Analytics
- Commits (Completed so far): Added way to save and store created assignments for future reference in db. Added styling changes for better integration.
![Image](https://github.com/user-attachments/assets/4bfa117b-30a0-4601-ba1a-2470a6081198)
- Saved question feature:
![{25123B17-B2C4-4A27-8EF2-42B139409DC6}](https://github.com/user-attachments/assets/8bfb7d18-ee5d-4d58-ba37-0bf9ffbf322c)
- Database work
![{FFEB47E2-70C3-45C9-800D-0E73DBE2F9B9}](https://github.com/user-attachments/assets/ce71c1c3-fd89-4fe0-91d7-466e5246ce08)
- Flowchart for visualization:
![{9DD5F4B7-5B90-4207-A925-2F1FF6445F16}](https://github.com/user-attachments/assets/36ca2224-a7f4-4858-a23f-9029ea2b9790)
- Requested db integration: https://github.com/CSA-Coders-2025/Planning-Repository-Issue-House-/issues/52
## To-Do Checklist/Future Plans:
- [x] Connect generator page to login system - no access to page without user login/cookies
- [x] Save assignments under each account in database so that users can only see the questions they have saved
- [x] Add answers to generated FRQ questions that can also be saved in db
- [x] Finish integrating with Synergy team
## Collegeboard FRQ Plan:
- Doing 2d arrays part 1 with Hanlun and Sharon
- Referencing 2015 FRQ Question 3 [link to frq 2015](https://secure-media.collegeboard.org/digitalServices/pdf/ap/ap15_frq_computer_science_a.pdf) to get idea of proper Collegeboard FRQs
- Coordinating and discussing with group for future plans and how we will approach teaching FRQs

**Comment by sharonkodali** [comment]
**Sharon Kodali** 

**Scrum master Evaluation**  
- our project team issue is detailed with specifics for each team member and how we are going to integrate 


**Analytics** 

![Image](https://github.com/user-attachments/assets/b00939f1-0257-4c35-bd17-2e29ee2e833f)


**My Feature** 
- Part of the seedtracker team 
- worked on the backend making sure out SQL
![Image](https://github.com/user-attachments/assets/81da2979-f88a-4b5a-aaa7-15e732eef7cf)




**To Do** 
- integrate into teacher toolkit backend 
- ALso integrate out grading system with the CSA synergy team 
- GradeRequest Column from the CSA synergy is created.


Issue for Mort ToolKit Planning Integration

https://github.com/orgs/CSA-Coders-2025/projects/3/views/9?pane=issue&itemId=88039461&issue=CSA-Coders-2025%7CPlanning-Repository-Issue-House-%7C23 


**Specific changes that need to be made** 
- CSA Synergy: Make an API to create a grade request
- CSA Synergy: Make assignments, not just events show up in calendar
- CSA Synergy: Make it so that students can view grades on the frontend
- CSA Synergy: Make it so that students can view assignments and submit them on the frontend
- Seed Tracker: Make it so that a GradeRequest (from CSA Synergy) is created

**Comment by miggysp** [comment]
Miheer 

Link to integration plans: https://github.com/orgs/CSA-Coders-2025/projects/3/views/9?pane=issue&itemId=89571985&issue=CSA-Coders-2025%7CPlanning-Repository-Issue-House-%7C69
Analytics:
![Image](https://github.com/user-attachments/assets/c935a082-044d-4929-b516-36f7180cfb93)
Analytics on github is back to the other account for some reason. I am going to debug that. 

Backend Contribution:
![Image](https://github.com/user-attachments/assets/2723e7c3-0a4c-4e68-96c0-63c6ebe5f0ff)


To Do:

Integrate student page with people database that everyones using. 
Work with synergy group so that the grades will also be integrated. 
create balance column in backend (integrate with new users db)
integrate frontend with gamify (make sure theme is consistent)
communicate w/ project group for future planning

Future Collegeboard FRQ Plan:
doing 2d arrays P2 with Beijan and Eshaan
Have identified collegeboard information.
Done so far:
met up with last tri group in order to discuss plans for integration
split up workload for integration:
